### ISSUE TITLE
Can you add a composer.json and packagist entry?

### ISSUE THREAD

**Issue by arendjantetteroo** [cumulio/cumul.io-sdk-php#1]
This would allow easier installation

**Comment by Kagaherk** [comment]
Added now -- see https://packagist.org/packages/cumulio/cumul.io-sdk-php
@arendjantetteroo -- can you verify the install works for you?

**Comment by arendjantetteroo** [comment]
@Kagaherk thanks. Can you add an autoload entry to composer.json? 
This would avoid seperatly needing a 
include('cumulio.php');

**Comment by arendjantetteroo** [comment]
composer require cumulio/cumul.io-sdk-php works fine, might want to add that to the Readme :)

**Comment by TBeeckmans** [comment]
We where looking to include the SDK into our Drupal 8 project. We want to be able to let the package, defined as requirement in the module, be installed by the composer located in the root of the project. 

The vendor folder is located outside of the docroot for security reasons. Unfortunately we faced the issue that the autoloader assumed the package was installed with another name (case sensitive: cumulio / Cumulio) and at another location (a location in the module itself instead of the vendor map at root level).
We have created a [pull request that resolves the issue](**https://github.com/cumulio/cumul.io-sdk-php/pull/3**).
